### PR TITLE
softbot_example final #880

### PR DESCRIPTION
**Pull request by brunofavs**
Softbot example implemented. Watch out to remove softbot repo out of your catkin_ws before testing to not have ambiguity.

### CODE REVIEW

**Comment by brunofavs** [comment]
I'm not sure why the images here have different heights... The RGB images are `1280x720`

https://github.com/lardemua/atom/blob/6d3e92d734c2a04ce7193fb59d2611e08ca6b3b7/atom_examples/softbot/README.md#L124-L130

On my end it looks great. On github it doesn't..

image

**Comment by brunofavs** [comment]
The link for for the updated dataset with the recent `transform` key added is in the issue
@miguelriemoliveira 

#908

**Comment by miguelriemoliveira** [comment]
Thanks @brunofavs ,

I will merge now.

**Comment by miguelriemoliveira** [comment]
Hi @brunofavs ,

some tips for a future PR.

I removed the .vscode folder. That should not be included.
Removed sparse_matrix from calibration folder. 
Removed utf from the configure file.

**Pull request merged**
