### PR TITLE
Creation of full evaluation 

### PR DESCRIPTION
**Pull request by manuelgitgomes**
Solves #500

### CODE REVIEW

**Comment by manuelgitgomes** [comment]
Hello @danifpdra and @miguelriemoliveira!

If this is not urgent, I will write documentation to the website first and then I will merge this!

**Comment by miguelriemoliveira** [comment]
Hi @manuelgitgomes ,

thanks. Documentation is always a good idea : - )

**Comment by manuelgitgomes** [comment]
Hello @miguelriemoliveira!
 
 Documentation is now online.
 I will merge this now.

**Comment by miguelriemoliveira** [comment]
Hi @manuelgitgomes ,

thanks. I read it but it sounds incomplete. Perhaps you should say this and that file are created, something like this.

**Comment by manuelgitgomes** [comment]
Ok, I will write a better introduction!

**Comment by miguelriemoliveira** [comment]
Thanks. But what I missed the most was a conclusion at the end.

**Comment by manuelgitgomes** [comment]
What do you mean? At the end of each evaluation or at the end of it all? 
And what should it be written on it?

**Comment by miguelriemoliveira** [comment]
Hi @manuelgitgomes ,

Right now it is:


Full evaluation
During its configuration, ATOM generates a launch file named full_evaluation.launch. This file configures every possible evaluation the system might have and carries it on. To run it:

...

I am missing a line at the end that says something like: After the evaluations are complete, you can find several csv files at location X. These files contain the results for the evaluations ... yada yada yada ...

**Comment by miguelriemoliveira** [comment]
also, it should say.

"you can run each evaluation independently". 
Depending on the modalities in the system, different evaluations will be possible to conduct.

Byu running all evaluations atom will automatically figure out which evaluations are possible for your system and run those.

**Comment by manuelgitgomes** [comment]
Done!

**Pull request merged**
