### PR TITLE
small change in dictionary keys

### PR DESCRIPTION
**Pull request by brunofavs**
Everything explained in #852

### CODE REVIEW

**Comment by Kazadhum** [comment]
Hi @brunofavs ! I just checked the data_collector node and it seems that it records the dataset with the attribute `joint_type` and not `xacro_joint_type`.

https://github.com/lardemua/atom/blob/dc6c33f609ad4ec80fa3d317453cc30bd95c8626/atom_calibration/src/atom_calibration/collect/data_collector.py#L460-L467

I believe the issue you found in https://github.com/lardemua/atom/issues/852 is a problem with that specific dataset and not with ATOM's source code in itself.


What do you think @miguelriemoliveira ?

**Comment by brunofavs** [comment]
I should add that I replaced the keyword in the dataset with the previous code and it worked again flawlessly. The question now is whether it was an isolated issue regarding this specific dataset or if there's a bug somewhere making this repeatable.

**Comment by manuelgitgomes** [comment]
> I believe the issue you found in #852 is a problem with that specific dataset and not with ATOM's source code in itself.

I am fairly certain that is what is happening, my datasets all have the `joint_type` attribute, so I would recommend closing this PR.

**Comment by brunofavs** [comment]
> I am fairly certain that is what is happening, my datasets all have the `joint_type` attribute, so I would recommend closing this PR.

Hey

Yeah after talking with @Kazadhum, I was also leaning towards closing the PR. I will leave the issue open waiting for @miguelriemoliveira to give feedback about this :

>  The question now is whether it was an isolated issue regarding this specific dataset or if there's a bug somewhere making this repeatable.

**Comment by miguelriemoliveira** [comment]
I think I changed it because I was using an "old" dataset that used a different field name. Please accept the PR, it looks good.

**Comment by brunofavs** [comment]
Reopening PR due to @miguelriemoliveira  request.

> I think I changed it because I was using an "old" dataset that used a different field name. Please accept the PR, it looks good.

What about the https://github.com/lardemua/atom/pull/853#issuecomment-1966807936 @Kazadhum made? Aren't there more places that use the keyword like the data_collector script referred in the referenced comment?

**Comment by miguelriemoliveira** [comment]
> Reopening PR due to @miguelriemoliveira request.
> 
> > I think I changed it because I was using an "old" dataset that used a different field name. Please accept the PR, it looks good.
> 
> What about the [#853 (comment)](https://github.com/lardemua/atom/pull/853#issuecomment-1966807936) @Kazadhum made? Aren't there more places that use the keyword like the data_collector script referred in the referenced comment?

Hi @brunofavs ,

I think the data collector script is the only where this happens, as its the data collector that creates the dataset and those fields. Actually, I remember changing that keyword sometime in december / january ... I think we can merge the PR, no problem. I will do it now.

**Comment by brunofavs** [comment]
Ok, sounds good then :)
Will delete the temporary branch.

**Pull request merged**
