### PR TITLE
#653 #679 #684 added package_name to dataset and optimized metadata

### PR DESCRIPTION
**Pull request by manuelgitgomes**
Package name was added to dataset by adding the `package_name` flag in collect_data.

I thought of two options on how to do this.
One would be to add an automatically filled field on the `config.yaml` file for the package_name, but for this I would need to change the programming logic behind the `configure_calibration_pkg`.
I opted not to do that and only add this to the dataset by, as stated, adding the `package_name` flag in collect_data.

The correct name is added automatically to `collect_data.launch`, so most users will not notice (nor care) about this new flag.
If a user uses an old calibration package, this does not break anything as a clause was added for the case of this flag being empty, in which defaults to the old package name `{robot_name}_calibration`.
If a user want to calibrate a dataset without the `package_name`, it also defaults to the old package name.

As this is a change on datasets, but not a breaking one, I took the liberty to change the dataset version from 2.0 to 2.1.

Alongside this, I added creation of metadata to initialization of class, instead of being during each saveCollection.
This is in accordance with some of the changes discussed in #679.
As I was already changing something in here, I decided to change this as well.

I tested the data collection in both old and new calibration packages, and tried calibration in 2.0 and 2.1 dataset versions.
Everything went smoothly as expected.

### CODE REVIEW

**Comment by miguelriemoliveira** [comment]
Hi @manuelgitgomes ,

About the package_name input argument. I think I have a better option.

See if you agree: 

You created a package_name input argument to be given in the collect_data.launch. This I think is because that's where we found that this information is needed. 

However, my argument is that this information should be useful perhaps in more that the collect_data stage. 
I now there is an issue that I cannot find right now about the writting of the optimized urdf file failing at the end of the calibrate script. There it would also be interesting to have the package_name information.

Thus, my suggestion is that we inject this information into the config file, and then it will be included in all dataset (since they contain a copy in the calibration_config field) and are accessible to all stages of the calibration procedure.

If we opt for this, what we would need to do is add this field package_name on the config.yml and put the proper value there when we run the create_calibration_pkg script.

Does it make sense to you? Does it sound like a better strategy?

**Comment by manuelgitgomes** [comment]
Hello @miguelriemoliveira, I understand and it does make sense.

However, I have one doubt in how to implement it.
I suppose this should be added in `create_calibration_pkg`, right?
So it is on the config file from the beginning.
If it is on the config file, I want to give users the option to change it (although they shouldn't).
But, however, this has a problem here:

https://github.com/lardemua/atom/blob/d5685b1a715e340b6ec9f88cebd68aba5c3bf9b6/atom_calibration/scripts/configure_calibration_pkg#L102-L107

Where to read the `config.yml`, the script already needs the package name.

What I can do is to change `args['config_file]` from a local path to a global path.
This is would be generated automatically for regular users, so no problem here.
For power users, they can give the script whichever config file they want, and it will read the package name from there.

What do you think?

**Comment by miguelriemoliveira** [comment]
> Hello @miguelriemoliveira, I understand and it does make sense.
> 
> However, I have one doubt in how to implement it. I suppose this should be added in `create_calibration_pkg`, right? 

Right, that's where we create the config.yml file. 


> So it is on the config file from the beginning. If it is on the config file, I want to give users the option to change it (although they shouldn't). 

Right, the value should be automatically filled and then in the commend near the field we should say "change this only if you know what you are doing" ...


> But, however, this has a problem here:
> 
> https://github.com/lardemua/atom/blob/d5685b1a715e340b6ec9f88cebd68aba5c3bf9b6/atom_calibration/scripts/configure_calibration_pkg#L102-L107
> 
> Where to read the `config.yml`, the script already needs the package name.

I see ...

> What I can do is to change `args['config_file]` from a local path to a global path. This is would be generated automatically for regular users, so no problem here. For power users, they can give the script whichever config file they want, and it will read the package name from there.

You mean change **args['config_file]** in the configure_calibration_pkg script, right?

I do not think so, because a global path would make the solution not portable. I mean, you do it for your computer and it resolves the global path, then I git pull and it does not work for me.

The configure_calibration_pkg already has the --name (which is the package name) argument included, and from the package name we get the path.

So, yes, in this case it is different, as we are not using the config file to get the package_name. 
But I think it will still work ... so I would keep it like that ...

perhaps I am missing something. If you want we can zoom about it tomorrow afternoon.

Also, since you are going to touch create_calibration_pkg, could you also implement #684 ?

**Comment by manuelgitgomes** [comment]
> So, yes, in this case it is different, as we are not using the config file to get the package_name.
> But I think it will still work ... so I would keep it like that ...

I agree, it would work, but it is still weird for me to have a parameter in the config yaml that cannot be changed..

What we can do is to remove the automatic `--name` flag, and give it based on the current package of the `configure` script, right?

**Comment by miguelriemoliveira** [comment]
> I agree, it would work, but it is still weird for me to have a parameter in the config yaml that cannot be changed..

I agree, it also sounds weird to me.
 
> What we can do is to remove the automatic `--name` flag, and give it based on the current package of the `configure` script, right?

But is this a way to solve the weirdness you describe above? I am confused. My suggestion is we do it together tomorrow morning or something.

What do you say?

**Comment by manuelgitgomes** [comment]
This PR now addresses #653 #679 and #684

Added package name to config.yml and subsequently removed it from collect_data.launch (#653)
To do this, I need to add jinja2 support for config.yml (#684)

Xacro reading was fixed by using the ATOM function readXacroFunction (#679)

I think this is all good, can @miguelriemoliveira or @Kazadhum verify?

**Comment by miguelriemoliveira** [comment]
Hi @manuelgitgomes ,

can you give me some hints on how to test? Honestly, we have so much going on I don't really know what I should test.

**Comment by manuelgitgomes** [comment]
> can you give me some hints on how to test? Honestly, we have so much going on I don't really know what I should test.

Hello! 
So, for now, try and create a dataset.
Possibly you would need to add `package_name` to the config.yml, or create the package all over again.

Then try to calibrate to see if everything goes as planned

**Comment by manuelgitgomes** [comment]
Hello @miguelriemoliveira 

I know this is not a good practice, but I need to merge this to carry on my work.
Please test it nevertheless and write issues if something is missing.

**Comment by miguelriemoliveira** [comment]
Hi @manuelgitgomes ,

I understand. Only now I was out of classes. You did well to advance.

**Comment by miguelriemoliveira** [comment]
@manuelgitgomes  you were right, we get an error like this 

```terminal
alueError: Your config file /home/mike/workspaces/catkin_ws/src/calibration/atom/atom_examples/rgb_hand_eye_system/rgb_hand_eye_system_calibration/calibration/config.yml appears to be corrupted. These mandatory parameters are missing: ['package_name']
Perhaps you should re-run:
 rosrun <my_robot>_calibration configure
```

when running

    roslaunch rgb_hand_eye_system_calibration collect_data.launch output_folder:=$ATOM_DATASETS/rgb_hand_eye_system/my_dataset overwrite:=true

Running configure will not work. I think I will have to manually add the package_name field to the config.yml.

**Pull request merged**
