### PR TITLE
Convert rosbag to ros1 if ros2 bag is passed

### PR DESCRIPTION
**Pull request by dimaxano**
As a ROS2 user, I've been using Atom for several months and I am super excited!

Here I added a conversion from rosbag2 format to rosbag1 so people can use their data recorded in ROS2 with Atom.

To make a conversion I use an external library [rosbags](https://github.com/cmrobotics/rosbags). That is a fork from [here](https://github.com/cmrobotics/rosbags). We do not use the upstream because of the [bug](https://gitlab.com/ternaris/rosbags/-/issues/52).

I'm happy to make a documentation page about setting up Atom for ROS2 users. Just not sure where to put it

### CODE REVIEW

**Comment by miguelriemoliveira** [comment]
Hi @dimaxano ,

thanks so much for your contribution. I will look into it and let you know our opinions, but I will need some time until later this week.

My comments for now are:

1. You added to the configure_calibration_pkg script a mechanism that detects if the bagfile is a rosbag2, and if so automatically convert it to rosbag1. 

It would more sense to me to have a separate script to convert the bagfile from ros2 to ros1 (it could be placed [here](https://github.com/lardemua/atom/tree/noetic-devel/atom_calibration/scripts/utilities)

That way a ros2 person would only have to convert their bag2 to bag1, then  run atom exactly the same way as others.

2. You also added a dockerfile. That would be out of the scope of atom or not? Why is the docker file needed? To run ros2?

Also, I ask @manuelgitgomes and @danifpdra to give me their input.

**Comment by dimaxano** [comment]
Hi @miguelriemoliveira,

Thank you very much for taking a brief look at the PR.

1. My motivation for doing rosbag conversion inside `configure_calibration_pkg` is to simplify users' lives (at least that is how it looks to me, I may be subjective) i.e. you just put whatever rosbag you have, Atom will eat any of them :)

But if you think it would be better to do it outside of Atom, I'm up to it. In that case, I'd only need to provide a clear set of instructions on how to set everything up, without actually modifying the source code.

2. The Dockerfile of ROS Noetic is made for ROS2 users to run Atom there, as I guess very few of them have a ROS1 system in close proximity. I'm ready to provide a thorough set of instructions for the documentation page on how to use it.

**Comment by miguelriemoliveira** [comment]
Thanks for the answers @dimaxano ,

lets hear @manuelgitgomes and @danifpdra 's opinions on these, then decide.

**Comment by danifpdra** [comment]
> Thanks for the answers @dimaxano ,
> 
> lets hear @manuelgitgomes and @danifpdra 's opinions on these, then decide.

Hi @miguelriemoliveira,

The idea seems good to me! In relation to the conversion being inside or outside the configure_calibration_pkg, from what I saw of the code, it doesn't really affect the way you run the code, you just have to give it either one the rosbag versions, so I would vote to keep it as it because it would be easier for the user to run and I don't see any advantage in having it separated. 

I think it also makes sense that the dockerfile is inside ATOM so that other people with ROS2 also can use it straight away.

**Comment by manuelgitgomes** [comment]
Hello to all!

First of all, thank you @dimaxano for using our framework and for contributing with this PR.

The code seems nice, simple and straight to the point.
I agree with @danifpdra that converting the rosbag inside is more convenient for the user.

Regarding the dockerfile, I really like it, as I already use a docker wrapper to run Atom (and other ros1 packages).
To have a standardized way to run it, it seems better than the system we have now.
@Kazadhum could also drop some insights into this, as he already developed docker systems for Atom.

Overall, I liked you PR and it can be merged IMO.

**Comment by miguelriemoliveira** [comment]
Thanks to both. @Kazadhum , any suggestions / comments on the docker file?

**Comment by Kazadhum** [comment]
Hello all!

First off, thank you once again @dimaxano for your contributions!

I think that both of them are great! Both of them make the end-user's experience easier and both seem clean to me! I am a big fan of using docker to run ATOM and other ROS software, so I'm all for adding a Dockerfile for users who might like to do the same!

As an addendum to this, would it make sense to also keep a repository on Docker Hub with a container image with the latest version of ATOM? It could be nice for users to have an environment automatically set up for their use of ATOM. I did something similar some time ago. The only less-than-user-friendly thing would be setting up X11 to actually see Gazebo and RViz, but I think I wrote something about that in my Docker Hub repo. That way, we could have an easily accessible, already built container image to use ATOM in the Docker Hub repository, as well as a Dockerfile for developers to build images after changin something. If you think it's a good idea, I'll create a separate issue for it. What do you think, @manuelgitgomes, @miguelriemoliveira, @danifpdra ?

Meanwhile, I think @dimaxano 's contributions are great and the code looks good to me.

**Comment by dimaxano** [comment]
Just rebased to resolve conflicts

**Comment by miguelriemoliveira** [comment]
Thanks again @dimaxano  for the great contribution.

We considered moving to ROS2 in the past, but the effort will be gigantic, so this new possibility you added is very useful.

I am going to accept the PR just now. Welcome to the list of ATOM contributors :- )!

**Comment by miguelriemoliveira** [comment]
Just improved the following after accepting the PR.

1. Changed print styles to conform with ATOM style (using atomError, colorama colors, etc)
2. Added new dependency rosbags to requirements.txt

**Pull request merged**
